P4EST_TEST -> JULIA_P4EST_TEST, P4EST_TEST_LIBP4EST -> JULIA_P4EST_TEST_LIBP4EST

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,7 +27,7 @@ concurrency:
 jobs:
   test:
     if: "!contains(github.event.head_commit.message, 'skip ci')"
-    name: ${{ matrix.os }} - ${{ matrix.p4est_test }} - Julia ${{ matrix.version }}
+    name: ${{ matrix.os }} - ${{ matrix.JULIA_P4EST_TEST }} - Julia ${{ matrix.version }}
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -42,7 +42,7 @@ jobs:
           - windows-latest
         arch:
           - x64
-        p4est_test:
+        JULIA_P4EST_TEST:
           - P4EST_JLL_MPI_DEFAULT
           # TODO: Clang; it looks like we do not build binaries in P4est_jll for OpenMPI_jll
           # - P4EST_JLL_MPI_OPENMPIJLL
@@ -54,14 +54,14 @@ jobs:
           #       versions of Julia, see
           #       https://github.com/JuliaPackaging/Preferences.jl/issues/40
           - version: '1.6'
-            p4est_test: P4EST_CUSTOM_MPI_CUSTOM
+            JULIA_P4EST_TEST: P4EST_CUSTOM_MPI_CUSTOM
           # Only selected tests on macOS and Windows, since not everything works
           # everywhere yet and we are most familiar with setting up custom
           # p4est and MPI builds on Linux
           - os: macos-latest
-            p4est_test: P4EST_CUSTOM_MPI_CUSTOM
+            JULIA_P4EST_TEST: P4EST_CUSTOM_MPI_CUSTOM
           - os: windows-latest
-            p4est_test: P4EST_CUSTOM_MPI_CUSTOM
+            JULIA_P4EST_TEST: P4EST_CUSTOM_MPI_CUSTOM
     steps:
       - uses: actions/checkout@v3
       - name: Set p4est release to run tests against
@@ -72,21 +72,21 @@ jobs:
         shell: bash
       - name: Set environment variables
         run: |
-          echo "Setting variables for '${{ matrix.p4est_test }}'..."
-          echo "P4EST_TEST=${{ matrix.p4est_test }}" >> $GITHUB_ENV
-          echo "P4EST_TEST=${{ matrix.p4est_test }}"
-          if [[ ${{ matrix.p4est_test }} == "P4EST_JLL_MPI_DEFAULT" ]]
+          echo "Setting variables for '${{ matrix.JULIA_P4EST_TEST }}'..."
+          echo "JULIA_P4EST_TEST=${{ matrix.JULIA_P4EST_TEST }}" >> $GITHUB_ENV
+          echo "JULIA_P4EST_TEST=${{ matrix.JULIA_P4EST_TEST }}"
+          if [[ ${{ matrix.JULIA_P4EST_TEST }} == "P4EST_JLL_MPI_DEFAULT" ]]
           then
             echo "(no additional environment variables required)"
-          elif [[ ${{ matrix.p4est_test }} == "P4EST_CUSTOM_MPI_DEFAULT" ]] || [[ ${{ matrix.p4est_test }} == "P4EST_CUSTOM_MPI_CUSTOM" ]]
+          elif [[ ${{ matrix.JULIA_P4EST_TEST }} == "P4EST_CUSTOM_MPI_DEFAULT" ]] || [[ ${{ matrix.JULIA_P4EST_TEST }} == "P4EST_CUSTOM_MPI_CUSTOM" ]]
           then
             P4EST_TMP=`pwd`/libp4est_tmp
             echo "P4EST_TMP=$P4EST_TMP" >> $GITHUB_ENV
             echo "P4EST_TMP=$P4EST_TMP"
-            echo "P4EST_TEST_LIBP4EST=$P4EST_TMP/prefix/lib/libp4est.so" >> $GITHUB_ENV
-            echo "$P4EST_TEST_LIBP4EST=$P4EST_TMP/prefix/lib/libp4est.so"
+            echo "JULIA_P4EST_TEST_LIBP4EST=$P4EST_TMP/prefix/lib/libp4est.so" >> $GITHUB_ENV
+            echo "$JULIA_P4EST_TEST_LIBP4EST=$P4EST_TMP/prefix/lib/libp4est.so"
           # TODO: Clang; remove
-          # elif [[ ${{ matrix.p4est_test }} == "P4EST_CUSTOM_USES_MPI" ]]; then
+          # elif [[ ${{ matrix.JULIA_P4EST_TEST }} == "P4EST_CUSTOM_USES_MPI" ]]; then
           #   echo "JULIA_P4EST_GENERATE_BINDINGS=yes" >> $GITHUB_ENV
           #   echo "JULIA_P4EST_GENERATE_BINDINGS=yes"
           #   P4EST_TMP=`pwd`/libp4est_tmp_uses_mpi
@@ -101,7 +101,7 @@ jobs:
           #   echo "JULIA_P4EST_MPI_INCLUDE=/usr/include/x86_64-linux-gnu/mpich" >> $GITHUB_ENV
           #   echo "JULIA_P4EST_MPI_INCLUDE=/usr/include/x86_64-linux-gnu/mpich"
           else
-            echo "ERROR: unknown test type ${{ matrix.p4est_test }}" >&2
+            echo "ERROR: unknown test type ${{ matrix.JULIA_P4EST_TEST }}" >&2
             exit 1
           fi
           echo "Done."
@@ -114,7 +114,7 @@ jobs:
       - uses: julia-actions/cache@v1
       - name: Install custom MPI library for testing
         run: |
-          if [[ ${{ matrix.p4est_test }} == "P4EST_CUSTOM_MPI_CUSTOM" ]]
+          if [[ ${{ matrix.JULIA_P4EST_TEST }} == "P4EST_CUSTOM_MPI_CUSTOM" ]]
           then
             sudo apt-get install -y openmpi-bin libopenmpi-dev
           fi
@@ -151,7 +151,7 @@ jobs:
       # - uses: coverallsapp/github-action@master
       #   with:
       #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     flag-name: run-${{ matrix.p4est_test }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}-${{ github.run_id }}
+      #     flag-name: run-${{ matrix.JULIA_P4EST_TEST }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}-${{ github.run_id }}
       #     parallel: true
       #     path-to-lcov: ./lcov.info
       # Instead, we use a more tedious approach:
@@ -160,11 +160,11 @@ jobs:
       # - Upload only the merged coverage report to Coveralls
       - shell: bash
         run: |
-          cp ./lcov.info ./lcov-${{ matrix.p4est_test }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.info
+          cp ./lcov.info ./lcov-${{ matrix.JULIA_P4EST_TEST }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.info
       - uses: actions/upload-artifact@v3
         with:
-          name: lcov-${{ matrix.p4est_test }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}
-          path: ./lcov-${{ matrix.p4est_test }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.info
+          name: lcov-${{ matrix.JULIA_P4EST_TEST }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}
+          path: ./lcov-${{ matrix.JULIA_P4EST_TEST }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.info
 
   finish:
     needs: test
